
export const CLIENT_COLORS = [
  'bg-blue-500',
  'bg-purple-500',
  'bg-green-500',
  'bg-yellow-500',
  'bg-red-500',
  'bg-indigo-500',
  'bg-blue-400',
  'bg-pink-500'
];

export const MONTH_NAMES_AR = ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"];
export const MONTH_NAMES_EN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

export const TRANSLATIONS = {
  ar: {
    appName: "حصيلة",
    appTagline: "نظم أرباحك في سحابة آمنة",
    dashboard: "الرئيسية",
    clients: "العملاء",
    history: "الأرشيف",
    reports: "التقارير",
    welcome: "أهلاً بك 👋",
    monthlySummary: "ملخص شهر",
    achievedBalance: "الرصيد المحقق",
    goal: "الهدف",
    completed: "المنجزة",
    ongoing: "الجارية",
    topClients: "أفضل العملاء",
    tasks: "مهام",
    addClient: "إضافة عميل",
    clientNamePlaceholder: "اسم العميل الجديد...",
    add: "إضافة",
    manageTasks: "إدارة المهام",
    noClients: "لا يوجد عملاء مضافين",
    archiveTitle: "أرشيف الأرباح",
    noArchive: "لا يوجد بيانات مؤرشفة حتى الآن.",
    targetReached: "تم تحقيق الهدف ✓",
    performanceReports: "تقارير الأداء",
    totalIncome: "إجمالي الدخل",
    monthlyAvg: "متوسط شهري",
    last6Months: "آخر 6 أشهر",
    incomeDistribution: "توزيع الدخل",
    smartAnalysis: "تحليلات ذكية",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    language: "اللغة / Language",
    changeLang: "English",
    confirmDelete: "هل تريد الحذف؟",
    confirmLogout: "هل تريد الخروج فعلاً؟",
    setGoalTitle: "حدد هدفك المالي لهذا الشهر",
    editGoalTitle: "تعديل الهدف المالي",
    goalPlaceholder: "كم تريد أن تجني؟",
    startTracking: "بدء التتبع",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    clientDetails: "تفاصيل العميل",
    totalEarned: "إجمالي المحصل",
    addTask: "إضافة مهمة جديدة",
    taskTitlePlaceholder: "عنوان المهمة...",
    price: "السعر",
    noTasks: "لا يوجد مهام لهذا العميل بعد",
    deleteTask: "حذف المهمة",
    months: MONTH_NAMES_AR
  },
  en: {
    appName: "Haseela",
    appTagline: "Organize your earnings in a secure cloud",
    dashboard: "Dashboard",
    clients: "Clients",
    history: "Archive",
    reports: "Reports",
    welcome: "Welcome back 👋",
    monthlySummary: "Summary for",
    achievedBalance: "Achieved Balance",
    goal: "Goal",
    completed: "Completed",
    ongoing: "Ongoing",
    topClients: "Top Clients",
    tasks: "tasks",
    addClient: "Add Client",
    clientNamePlaceholder: "New client name...",
    add: "Add",
    manageTasks: "Manage Tasks",
    noClients: "No clients added yet",
    archiveTitle: "Earnings Archive",
    noArchive: "No archived data yet.",
    targetReached: "Goal Achieved ✓",
    performanceReports: "Performance Reports",
    totalIncome: "Total Income",
    monthlyAvg: "Monthly Avg",
    last6Months: "Last 6 Months",
    incomeDistribution: "Income Distribution",
    smartAnalysis: "Smart Analysis",
    settings: "Settings",
    logout: "Logout",
    language: "Language / اللغة",
    changeLang: "العربية",
    confirmDelete: "Are you sure you want to delete?",
    confirmLogout: "Are you sure you want to logout?",
    setGoalTitle: "Set your financial goal",
    editGoalTitle: "Edit financial goal",
    goalPlaceholder: "How much do you want to earn?",
    startTracking: "Start Tracking",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    clientDetails: "Client Details",
    totalEarned: "Total Earned",
    addTask: "Add New Task",
    taskTitlePlaceholder: "Task title...",
    price: "Price",
    noTasks: "No tasks for this client yet",
    deleteTask: "Delete Task",
    months: MONTH_NAMES_EN
  }
};
